### ISSUE TITLE
sf2.smx not find dhooks but is installed

### ISSUE THREAD

**Issue by argos76** [KitRifty/slender-fortress#13]
linux server under debian

ls -lsa dhooks*
248 -rwx------ 1 **\* **\* 252479 oct 18 10:07 dhooks.ext.so

sm plugins load sf2
[SM] Plugin sf2.smx failed to load: Required extension "dhooks" file("dhooks.ext") not running.

**Comment by Glubbable** [comment]
Have you tried adding dhooks.autoload to the extensions folder?

**Comment by argos76** [comment]
Not. I download the latest version dhooks-2.0.3-hg79-linux.tar.gz
dhooks.autoload not found in tar file, and I not know what need to add.
Now I do touch hooks.autoload for create, but the server does not start correctly. 
At loading tf2items is frozen and not go further.
dhoooks is not compatible with tf2items or sdkhooks?
I need to add something in the dhooks.autoload file? Any suggestions?
Thank you for help.

**Comment by Glubbable** [comment]
dhooks.autoload doesnt need to contain anything. And dhooks is perfectly compatible with tf2items and sdkhooks since the gamemode uses all 3 of them. Have you tried verifying your srcds install aswell?

I don't exactly see how I can help you with this problem since its an issue with your server refusing to load extensions, and that can happen for a ton of reasons.

**Comment by argos76** [comment]
ok. Thank you for the information.
I removed dhooks from the server and they starts properly.
I am now certain that the problem is dhoooks.
He found alliedmods forum that other people are having problems with it in the last month. 
I go try for other side. 
You can close this issue.
Thank you.
